spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      encoding: utf-8
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot